#!/usr/bin/bash

cp -R OldSecondary secondary1
cp -R OldSecondary secondary2
cp -R OldSecondary secondary3
cp -R OldSecondary secondary4
cp -R OldSecondary secondary5
cp -R OldSecondary secondary6
cp -R OldSecondary secondary7
cp -R OldSecondary secondary8
cp -R OldSecondary secondary9
cp -R OldSecondary secondary0
cp -R OldSecondary secondaryq
cp -R OldSecondary secondaryw
cp -R OldSecondary secondarye
cp -R OldSecondary secondaryr
cp -R OldSecondary secondaryt
cp -R OldSecondary secondaryy
cp -R OldSecondary secondaryu
cp -R OldSecondary secondaryi
cp -R OldSecondary secondaryo
cp -R OldSecondary secondaryp
cp -R OldSecondary secondarya
cp -R OldSecondary secondarys
cp -R OldSecondary secondaryd
cp -R OldSecondary secondaryf
cp -R OldSecondary secondaryg
cp -R OldSecondary secondaryh
cp -R OldSecondary secondaryj
cp -R OldSecondary secondaryk
cp -R OldSecondary secondaryl
cp -R OldSecondary secondaryz
cp -R OldSecondary secondaryx
cp -R OldSecondary secondaryc
cp -R OldSecondary secondaryv
cp -R OldSecondary secondaryb
cp -R OldSecondary secondaryn
cp -R OldSecondary secondarym
